
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 31 22:25:02 CEST 2014
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TESIS = 5;
  public static final int INT2STR = 33;
  public static final int UMINUS = 35;
  public static final int CLOG = 37;
  public static final int PC = 3;
  public static final int INTERSEC = 23;
  public static final int DECL = 15;
  public static final int NOT = 11;
  public static final int AND = 9;
  public static final int IGUAL = 32;
  public static final int TYPE = 40;
  public static final int IN = 21;
  public static final int OR = 10;
  public static final int EMPTYSET = 34;
  public static final int DIV = 29;
  public static final int BEGIN = 6;
  public static final int IF = 12;
  public static final int EOF = 0;
  public static final int ASIG = 8;
  public static final int CARD = 24;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int COMA = 2;
  public static final int MENOS = 27;
  public static final int MENOR = 31;
  public static final int IDENT = 39;
  public static final int CSTR = 38;
  public static final int MAYOR = 30;
  public static final int BRAC = 19;
  public static final int UNION = 22;
  public static final int CINT = 36;
  public static final int WHILE = 16;
  public static final int THEN = 13;
  public static final int PROG = 14;
  public static final int LOWEST_ELEM = 25;
  public static final int END = 7;
  public static final int KET = 20;
  public static final int PAREN = 4;
  public static final int PRINT = 18;
  public static final int DO = 17;
  public static final int MAS = 26;
}

